## Employee Attrition Problem

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
df = pd.read_excel("http://139.59.22.214/wp-content/uploads/2018/05/TakenMind-Python-Analytics-Problem-case-study-1-1.xlsx")

In [10]:
# Preview the top of the dataset
df.head()

  The data is for company X which is trying to control attrition. There are two sets of data: "Existing employees" and "Employees who have left". Following attributes are available for every employee.
0                                 Satisfaction Level
1                                    Last evaluation
2                                 Number of projects
3                              Average monthly hours
4                          Time spent at the company